"""Add member roles and tenant invitations.

Revision ID: ab0c7e1db9a6
Revises: c7bdcfd18f01
Create Date: 2026-09-26 23:21:13.895113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab0c7e1db9a6"
down_revision: str | Sequence[str] | None = "c7bdcfd18f01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_tenant_invitations_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_invitations_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_invitations")),
        sa.UniqueConstraint("tenant_id", "email", name=op.f("uq_tenant_invitations_tenant_id")),
    )
    op.create_index(
        op.f("ix_tenant_invitations_email"), "tenant_invitations", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_invitations_tenant_id"), "tenant_invitations", ["tenant_id"], unique=False
    )
    op.add_column(
        "tenant_members",
        sa.Column("role", sa.String(length=16), server_default="member", nullable=False),
    )
    # Until now every member was the account that created its tenant: its admin.
    op.execute("UPDATE tenant_members SET role = 'admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_members", "role")
    op.drop_index(op.f("ix_tenant_invitations_tenant_id"), table_name="tenant_invitations")
    op.drop_index(op.f("ix_tenant_invitations_email"), table_name="tenant_invitations")
    op.drop_table("tenant_invitations")
    # ### end Alembic commands ###
