"""Add the tenant's mediator.

Revision ID: c7a730530f5e
Revises: 1382dde905a7
Create Date: 2026-09-27 20:07:05.506272

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7a730530f5e"
down_revision: str | Sequence[str] | None = "1382dde905a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("mediator_url", sa.String(length=2048), nullable=True))
    op.add_column("tenants", sa.Column("mediator_did", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "mediator_did")
    op.drop_column("tenants", "mediator_url")
    # ### end Alembic commands ###
