"""Link every issuer and verifier to one of its tenant's identities.

Revision ID: a931213af61b
Revises: c7a730530f5e
Create Date: 2026-09-27 20:33:49.148972

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a931213af61b"
down_revision: str | Sequence[str] | None = "c7a730530f5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    for table in ("issuers", "verifiers"):
        op.add_column(table, sa.Column("identity_id", sa.Uuid(), nullable=True))
        # Each one that already exists gets an identity of its own, named like
        # it — what creating one does from now on.
        op.execute(f"UPDATE {table} SET identity_id = gen_random_uuid()")
        op.execute(
            f"""
            INSERT INTO identities (id, tenant_id, name, created_at, updated_at)
            SELECT identity_id, tenant_id, name, created_at, now() FROM {table}
            """
        )
        op.alter_column(table, "identity_id", nullable=False)
        op.create_index(op.f(f"ix_{table}_identity_id"), table, ["identity_id"], unique=False)
        op.create_foreign_key(
            op.f(f"fk_{table}_identity_id_identities"),
            table,
            "identities",
            ["identity_id"],
            ["id"],
            ondelete="RESTRICT",
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_verifiers_identity_id_identities"), "verifiers", type_="foreignkey")
    op.drop_index(op.f("ix_verifiers_identity_id"), table_name="verifiers")
    op.drop_column("verifiers", "identity_id")
    op.drop_constraint(op.f("fk_issuers_identity_id_identities"), "issuers", type_="foreignkey")
    op.drop_index(op.f("ix_issuers_identity_id"), table_name="issuers")
    op.drop_column("issuers", "identity_id")
    # ### end Alembic commands ###
