"""Add the users' alias.

Revision ID: 1382dde905a7
Revises: cf7cd7fa8f67
Create Date: 2026-09-27 19:57:43.168098

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1382dde905a7"
down_revision: str | Sequence[str] | None = "cf7cd7fa8f67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("alias", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "alias")
    # ### end Alembic commands ###
